### ISSUE TITLE
关于尺寸和分辨率的问题

### ISSUE THREAD

**Issue by jilei6** [tianheg/chatgpt-text-to-midjourney-image#1]
Replicate 上构建的image的分辨率能调整吗？

**Comment by tianheg** [comment]
我想答案在这里 https://replicate.com/prompthero/openjourney/api

**Comment by tianheg** [comment]
你仔细看我给你的链接，它的prompt例子中有 `4 k resolution`

**Comment by tianheg** [comment]
这个我不太清楚，我的这个repo上游是 https://github.com/barretlee/chatgpt-text-to-midjourney-image，你可以问问他

**Comment by jilei6** [comment]
> 这个我不太清楚，我的这个repo上游是 https://github.com/barretlee/chatgpt-text-to-midjourney-image ，你可以问问他

好的，非常感谢及时且专业的回复
